### ISSUE TITLE
Fails when watching for changes

### ISSUE THREAD

**Issue by tomsmedleyy** [olivermarkrichman/ec2-deploy#1]
Can't watch and re-upload for some reason, have to recall the package each time it fails to get it to work. Image below shows fault that's occurring:

![57576609999__B964AC38-DEEE-495F-9697-CEE51577F4AD](https://user-images.githubusercontent.com/30045894/55296490-15005a80-5412-11e9-9666-cdb0405dadb4.jpg)

**Comment by olivermarkrichman** [comment]
This has been resolved now - bug involving hard coded directory name needed to be switched out for the directory name provided.
